### ISSUE TITLE
Issue while trying run jUnit tools from eclipse

### ISSUE THREAD

**Issue by bssoft82** [junit-tools-team/junit-tools#2]
Java Model Exception: Java Model Status [Invalid name specified: ]
	at org.eclipse.jdt.internal.core.JavaModelOperation.runOperation(JavaModelOperation.java:786)
	at org.eclipse.jdt.internal.core.CompilationUnit.createPackageDeclaration(CompilationUnit.java:440)
	at org.junit.tools.generator.TestClassGenerator.generate(TestClassGenerator.java:173)
	at org.junit.tools.base.MainController$1.run(MainController.java:174)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:119)

Java Model Exception: Java Model Status [Invalid name specified: ]
	at org.eclipse.jdt.internal.core.JavaModelOperation.runOperation(JavaModelOperation.java:786)
	at org.eclipse.jdt.internal.core.CompilationUnit.createPackageDeclaration(CompilationUnit.java:440)
	at org.junit.tools.generator.TestClassGenerator.generate(TestClassGenerator.java:173)
	at org.junit.tools.base.MainController$1.run(MainController.java:174)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:119)

  org.junit.tools.base.JUTException: Java Model Exception: Java Model Status [Invalid name specified: ]
  	at org.eclipse.jdt.internal.core.JavaModelOperation.runOperation(JavaModelOperation.java:786)
  	at org.eclipse.jdt.internal.core.CompilationUnit.createPackageDeclaration(CompilationUnit.java:440)
  	at org.junit.tools.generator.TestClassGenerator.generate(TestClassGenerator.java:173)
  	at org.junit.tools.base.MainController$1.run(MainController.java:174)
  	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:119)
  
  	at org.junit.tools.base.MainController.generateTestclass(MainController.java:195)
  	at org.junit.tools.base.MainController.generateTestclass(MainController.java:102)
  	at org.junit.tools.handler.GenerateTestClassHandler.execute(GenerateTestClassHandler.java:49)
  	at org.eclipse.ui.internal.handlers.HandlerProxy.execute(HandlerProxy.java:295)
  	at org.eclipse.ui.internal.handlers.E4HandlerProxy.execute(E4HandlerProxy.java:90)
  	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  	at java.lang.reflect.Method.invoke(Method.java:498)
  	at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:55)
  	at org.eclipse.e4.core.internal.di.InjectorImpl.invokeUsingClass(InjectorImpl.java:282)
  	at org.eclipse.e4.core.internal.di.InjectorImpl.invoke(InjectorImpl.java:264)
  	at org.eclipse.e4.core.contexts.ContextInjectionFactory.invoke(ContextInjectionFactory.java:132)
  	at org.eclipse.e4.core.commands.internal.HandlerServiceHandler.execute(HandlerServiceHandler.java:152)
  	at org.eclipse.core.commands.Command.executeWithChecks(Command.java:494)
  	at org.eclipse.core.commands.ParameterizedCommand.executeWithChecks(ParameterizedCommand.java:488)
  	at org.eclipse.e4.core.commands.internal.HandlerServiceImpl.executeHandler(HandlerServiceImpl.java:210)
  	at org.eclipse.e4.ui.workbench.renderers.swt.HandledContributionItem.executeItem(HandledContributionItem.java:433)
  	at org.eclipse.e4.ui.workbench.renderers.swt.AbstractContributionItem.handleWidgetSelection(AbstractContributionItem.java:454)
  	at org.eclipse.e4.ui.workbench.renderers.swt.AbstractContributionItem$3.handleEvent(AbstractContributionItem.java:482)
  	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
  	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4418)
  	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1079)
  	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4236)
  	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3824)
  	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$4.run(PartRenderingEngine.java:1121)
  	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
  	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1022)
  	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:150)
  	at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:693)
  	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
  	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:610)
  	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:148)
  	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:138)
  	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
  	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
  	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
  	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:388)
  	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:243)
  	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  	at java.lang.reflect.Method.invoke(Method.java:498)
  	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:673)
  	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:610)
  	at org.eclipse.equinox.launcher.Main.run(Main.java:1519)

**Comment by robertstreng** [comment]
We've fixed the problem. The change will be released next week.

**Comment by robertstreng** [comment]
Issue is fixed and a new version is available for eclipse (1.0.5)

**Comment by bssoft82** [comment]
Thanks team for fixing. I would certainly try this out and share the update
asap.
